### ISSUE TITLE
Good Job

### ISSUE THREAD

**Issue by Giblob** [FluffyFoxUwU/FluffyLauncher#1]
### **_`### _### **### no issue its just cool**_`_**

**Comment by FoxieFlakey** [comment]
could you tell a bit who are you i couldnt find anything about you? (assuming you cant just stumble this from google)

**Comment by Giblob** [comment]
> could you tell a bit who are you i couldnt find anything about you? (assuming you cant just stumble this from google)

yeah im from the lua scripting server, just wanted to me nice

**Comment by FoxieFlakey** [comment]
> > could you tell a bit who are you i couldnt find anything about you? (assuming you cant just stumble this from google)
> 
> yeah im from the lua scripting server, just wanted to me nice

ok UwU

**Comment by Giblob** [comment]
> > > could you tell a bit who are you i couldnt find anything about you? (assuming you cant just stumble this from google)
> > 
> > 
> > yeah im from the lua scripting server, just wanted to me nice
> 
> ok UwU

UwU
:)
